apiVersion: apps/v1
kind: Deployment
metadata:
  name: infrastore
  namespace: infrastore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infrastore
  template:
    metadata:
      labels:
        app: infrastore
    spec:
      securityContext:      # section makes the pod nonroot
        runAsNonRoot: true  # enforces container to be nonroot
        runAsUser: 1000     # userid of user (not 0), 1000 is standard
        runAsGroup: 1000    # groupid of user (not 0), 1000 is standard
      containers:
      - name: infrastore
        image: saheerbabu/infrastore:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: infrastore-secret
              key: admin-password
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: infrastore-secret
              key: secret-key
        - name: DJANGO_SUPERUSER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: infrastore-config
              key: DJANGO_SUPERUSER_USERNAME
        volumeMounts:
        - name: media
          mountPath: /app/media
        - name: db
          mountPath: /app/db
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: infrastore-media-pvc
      - name: db
        persistentVolumeClaim:
          claimName: infrastore-db-pvc

